= Культура глобальных вызовов
:description: Запустить дело или проект в одной стране плюс минус понятно, но сделать её масштабируемой на весь мир, работающей на стыке разных культур - ещё интереснее.

== Экспорт для малого и среднего бизнеса – Иррациональный вызов – в России денег хватает

При том что в России достаточно денег
Почему то _иррационально_ хочется что-то делать за рубежом
Почему?

== Интерес из детства – новый мир – исследователя

Любопытство
Последние зёрна романтике в мире где нет белых пятен

Экспортеры сейчас ведь В прошлом Купцы и Путешественники

Колумбы
Беринги

Классно себя такими ощущать )
Это же по сути как попасть в море, неизвестное пространство, почувствовать себя исследователем
Это всё про Психологию Бессознательного - Счастье – стать частью огромного и многообразного Мира 

И при этом придерживаться рационального стиля мышления (Психологии Разума) и обустраивать свой был таким образом, чтобы чувствовать себя как дома в разных точках мира и культурах

== Преодоление и интересные сложности – Докопаться до сути в контексте разных культур

В России уже натренирована нейронка в отношениях и ты чувствуешь как и с кем общаться
Отпускаешь тормоза где-то 

За рубежом
В силу разности культур
Приходится себя контролировать значительно больше

Вежливость как необходимый компонент
Продуманность формулировок
Точность образов в презентациях - Психология Разума

Сдержанность и самоконтроль - важный навык Психологии Воли
Спартак Джованьоли и откровение о превосходестве легиона над необученными войсками

== Значительные различия в культуре – возможность для российских решений на стыке

Смотреть в корень
Освободиться от наносных стереотипов, которых нет за рубежом

== Попытки - удачные и неудачные

== Стратегия – 

=== Первый шаг – образование, обучение детей и переквалификация кадров 

Очевидно позитивный контекст

=== Вовлечение партнёров

=== Развёртывание инфраструктуры

=== Долгосрочный источник финансирования ???

== Моменты счастья на стыке культур

Люксембург
Бахрейн
Вьетнам

==
